# syntax=docker/dockerfile:1.7

FROM nginx:1.27-alpine

COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY apps/mobile/dist /usr/share/nginx/html/mobile
COPY apps/admin/dist /usr/share/nginx/html/admin

EXPOSE 80
